name: Validation Monitoring Stack to Production

on:
  workflow_dispatch:


jobs:
  # ==========================================
  # PrometheusとNginxの設定ファイル検証フェーズ
  # ==========================================
  validate-configs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: Create Network(Actions)
        run: docker network create mynetwork
      
      - name: Integration test
        run: docker compose --profile dev up -d
  
      - name: Validate Prometheus config file
        run: docker exec prometheus promtool check config /etc/prometheus/prometheus.yml
  
      - name: Validate Nginx config file
        run: docker exec dev-nginx nginx -t
  
      - name: Check Prometheus API
        run: curl -fsS http://localhost:9090/api/v1/status/runtimeinfo
  
      - name: Check Grafana API
        run: curl -fsS http://localhost:3000/api/health
  
      - name: Docker Compose down
        run: docker compose --profile dev down
  
